name: Auto Post Cracked

on:
  schedule:
    - cron: '*/30 * * * *'   # toutes les 30 minutes
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Installer dépendances
        run: npm install

      - name: Lancer le bot
        env:
          COOKIES_JSON: ${{ secrets.COOKIES_JSON }}
          PUPPETEER_EXEC_PATH: /usr/bin/chromium-browser
        run: node bump.js
